# Generated by Django 6.0.3 on 2026-03-04 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("group", "Group"), ("knockout", "Knockout")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("index", models.PositiveIntegerField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("complete", "Complete"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["index"],},
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nominations_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nominations_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approved_from_nomination",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrant",
                        to="tournaments.nomination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opens_at", models.DateTimeField(db_index=True)),
                ("closes_at", models.DateTimeField(db_index=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("finalized", "Finalized"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("result_home_votes", models.PositiveIntegerField(default=0)),
                ("result_away_votes", models.PositiveIntegerField(default=0)),
                ("tie_extension_used", models.BooleanField(default=False)),
                ("decided_by_host", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_entrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="tournaments.group",
                    ),
                ),
                (
                    "home_entrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "winner_entrant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="won_matches",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.stage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="tournaments.stage",
            ),
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("nomination", "Nomination"),
                            ("group", "Group stage"),
                            ("knockout", "Knockout"),
                            ("complete", "Complete"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("public_results", "Public results"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "public_slug",
                    models.SlugField(blank=True, max_length=64, unique=True),
                ),
                ("public_enabled_at", models.DateTimeField(blank=True, null=True)),
                ("time_zone", models.CharField(default="Europe/London", max_length=64)),
                (
                    "nomination_limit_per_participant",
                    models.PositiveIntegerField(default=5),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournaments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stage",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nominations",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="entrant",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entrants",
                to="tournaments.tournament",
            ),
        ),
        migrations.CreateModel(
            name="TournamentInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("host", "Host"), ("participant", "Participant")],
                        default="participant",
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournament_invites_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournament_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("host", "Host"), ("participant", "Participant")],
                        db_index=True,
                        default="participant",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("removed", "Removed"),
                            ("banned", "Banned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chosen_entrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes_received",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="tournaments.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupEntrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_participations",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_entrants",
                        to="tournaments.group",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["group"], name="tournaments_group_i_28f221_idx"
                    ),
                    models.Index(
                        fields=["entrant"], name="tournaments_entrant_c89cc2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "entrant"),
                        name="uq_groupentrant_group_entrant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                ("votes_for", models.PositiveIntegerField(default=0)),
                ("votes_against", models.PositiveIntegerField(default=0)),
                (
                    "entrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_standings",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="tournaments.group",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["group"], name="tournaments_group_i_beded4_idx"
                    ),
                    models.Index(
                        fields=["entrant"], name="tournaments_entrant_3adb8e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "entrant"),
                        name="uq_groupstanding_group_entrant",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["state", "closes_at"], name="tournaments_state_997044_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["stage", "state"], name="tournaments_stage_i_188a9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["group", "state"], name="tournaments_group_i_4f9030_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("stage", "name"), name="uq_group_stage_name"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["visibility", "public_slug"],
                name="tournaments_visibil_12cc0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(
                fields=["tournament", "type", "status"],
                name="tournaments_tournam_7d0313_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("tournament", "index"), name="uq_stage_tournament_index"
            ),
        ),
        migrations.AddIndex(
            model_name="nomination",
            index=models.Index(
                fields=["tournament", "status"], name="tournaments_tournam_47834d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomination",
            index=models.Index(
                fields=["tournament", "submitted_by"],
                name="tournaments_tournam_9a36c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entrant",
            index=models.Index(
                fields=["tournament", "is_active"],
                name="tournaments_tournam_affc71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentinvite",
            index=models.Index(
                fields=["tournament", "status"], name="tournaments_tournam_8ae7ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentinvite",
            index=models.Index(
                fields=["email", "status"], name="tournaments_email_a2f59e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentmembership",
            index=models.Index(
                fields=["tournament", "status", "role"],
                name="tournaments_tournam_428d45_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentmembership",
            constraint=models.UniqueConstraint(
                fields=("tournament", "user"), name="uq_membership_tournament_user"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["match"], name="tournaments_match_i_47e99e_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["user"], name="tournaments_user_id_ae8736_idx"),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("match", "user"), name="uq_vote_match_user"
            ),
        ),
    ]
